class ImportacaoErrorCode:
    INVALID_PAYLOAD = "INVALID_PAYLOAD"
    EMPTY_FILE = "EMPTY_FILE"
    MAX_ROWS_EXCEEDED = "MAX_ROWS_EXCEEDED"
    INVALID_ROW = "INVALID_ROW"
    INVALID_TYPE = "INVALID_TYPE"
    REQUIRED_FIELD = "REQUIRED_FIELD"
    INVALID_NUMBER = "INVALID_NUMBER"
    INVALID_PRICE = "INVALID_PRICE"
    INVALID_SERVICE = "INVALID_SERVICE"
    CATEGORY_NOT_FOUND = "CATEGORY_NOT_FOUND"
    UNIT_NOT_FOUND = "UNIT_NOT_FOUND"
    TAX_NOT_FOUND = "TAX_NOT_FOUND"
    WAREHOUSE_NOT_FOUND = "WAREHOUSE_NOT_FOUND"
    DUPLICATE_CODE_IN_FILE = "DUPLICATE_CODE_IN_FILE"
    DUPLICATE_NAME_IN_FILE = "DUPLICATE_NAME_IN_FILE"
    CODE_ALREADY_EXISTS = "CODE_ALREADY_EXISTS"
    NAME_ALREADY_EXISTS = "NAME_ALREADY_EXISTS"
    INVALID_MATERIAL_TYPE = "INVALID_MATERIAL_TYPE"
    INVALID_STOCK = "INVALID_STOCK"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    IMPORT_FAILED = "IMPORT_FAILED"


class ImportacaoWarningCode:
    LOW_INITIAL_STOCK = "LOW_INITIAL_STOCK"
    SALE_PRICE_EMPTY = "SALE_PRICE_EMPTY"
    COST_PRICE_ZERO = "COST_PRICE_ZERO"
    NO_WAREHOUSE_FOR_ZERO_STOCK = "NO_WAREHOUSE_FOR_ZERO_STOCK"
    DEFAULT_WAREHOUSE_APPLIED = "DEFAULT_WAREHOUSE_APPLIED"


# Limites de segurança para evitar sobrecarga ou DoS
MAX_IMPORT_ROWS = 1000

TIPOS_PRODUTO_PERMITIDOS = ('Consumivel', 'Acabado', 'Revenda', 'Material')
TIPOS_MATERIAL_PERMITIDOS = ('Reutilizavel', 'Consumivel')
SERVICOS_PERMITIDOS = ('ABASTECIMENTO', 'COZINHA', 'PASTELARIA', 'BAR')
